// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    // "aws_project_region": "us-east-2",
    // "aws_cognito_identity_pool_id": "us-east-2:f7b98dd3-779d-481f-870e-3a1602a9f73e",
    // "aws_cognito_region": "us-east-2",
    // "aws_user_pools_id": "us-east-2_q6TuFU6GN",
    // "aws_user_pools_web_client_id": "28jubg8rsc7ist1mmi1uk314u7",
    // "oauth": {},
    // "aws_user_files_s3_bucket": "reunidos-aws6456b53dff1f4fdb9d8d24271450a462awsres-awsres",
    // "aws_user_files_s3_bucket_region": "us-east-2"
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6d78f5b6-3417-479e-a4a6-eafbf23ecb5a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hNbmSD2bN",
    "aws_user_pools_web_client_id": "3bgnm0p310fmviktqqmaqcqfvu",
    "oauth": {},
    "aws_user_files_s3_bucket": "reunidos-panel-webc2c5860a972d439496174bc218073web-reunidos",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
